### ISSUE TITLE
app wrapper doesn't enable goerli

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/assemble-package#19]
@dblodorn sorry for not making the pull request directly, but line 9 of [AppWrapper.tsx](https://github.com/public-assembly/assemble-package/blob/main/examples/nextjs/src/components/AppWrapper.tsx) in the examples/nextjs (assume same for react too) should have chain.goerli as well so that the test apps are compatible with testnet. without this u cant use goerli in local dev, just burned an hour or so figuring this out 

photo of where it needs to be added
<img width="676" alt="Screen Shot 2022-09-23 at 12 50 03 AM" src="https://user-images.githubusercontent.com/93691906/191914585-4f9fff1e-3f3b-408b-b403-fd06fd8c4f96.png">

**Comment by 0xTranqui** [comment]
same issue exists in the neosound-sandbox, and potentially other repos as well i havent checked

**Comment by 0xTranqui** [comment]
ive adjust the repos ive been working on to account for this update

**Comment by dblodorn** [comment]
Sounds good i'll take a look and add to the template
