### ISSUE TITLE
Clicking the examples link results in an error

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/assemble-package#38]
Booting up the next app is successful, but navigating to localhost:3000/examples results in an error.

<img width="988" alt="CleanShot 2022-12-08 at 09 55 34@2x" src="https://user-images.githubusercontent.com/37086973/206478777-1ffad0a9-dce3-498f-817c-14c25d921c61.png">

**Comment by dblodorn** [comment]
Oh shoot - let me look into this.

The new setup is working in erc721 display components... fyi. But this repo needs fixing

**Comment by salieflewis** [comment]
Hmm, okay. For erc721 display components, did you just go in and change things in the react-web3-package, or created a new package from the get go?

I may have also run into another error when trying to initialize a fresh package, but I could've also missed a step.

**Comment by dblodorn** [comment]
@salieflewis Got this working by adding this to the next.config.js

https://github.com/martpie/next-transpile-modules

```
/** @type {import('next').NextConfig} */

const withTM = require('next-transpile-modules')(['sample-package'])

const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  webpack: (config) => {
    config.module.rules.push({
      test: /\.(md|mdx)?$/,
      use: [
        {
          loader: '@mdx-js/loader',
          /** @type {import('@mdx-js/loader').Options} */
          options: {},
        },
      ],
    })
    return config
  },
}

module.exports = withTM(nextConfig)

```
